// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilhytxiysetjxkawqeee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaHl0eGl5c2V0anhrYXdxZWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTE2OTksImV4cCI6MjA2NDc2NzY5OX0.T_RwFyrVkIEOquWrE97ebLL_qasMH5uyKmxYHlG2brs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);